"""edit Workshop; Round_Table tables

Revision ID: b92350eb9ae1
Revises: f27321b12feb
Create Date: 2017-09-03 14:44:38.866958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b92350eb9ae1'
down_revision = 'f27321b12feb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('round_tables', sa.Column('available_position', sa.Integer(), nullable=True))
    op.add_column('workshops', sa.Column('available_positions', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workshops', 'available_positions')
    op.drop_column('round_tables', 'available_position')
    # ### end Alembic commands ###
