"""add new table

Revision ID: 25c53c092ce1
Revises: b92350eb9ae1
Create Date: 2017-09-05 12:58:17.457348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25c53c092ce1'
down_revision = 'b92350eb9ae1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('passes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('passes', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('passes')
    # ### end Alembic commands ###
