"""initial migration

Revision ID: b7df43043785
Revises: 
Create Date: 2017-09-02 08:19:26.129933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7df43043785'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('beverages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('beverage', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('beverage')
    )
    op.create_table('school_grades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('staff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('user_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type')
    )
    op.create_table('round_tables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table', sa.String(), nullable=True),
    sa.Column('grade_allowed', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['grade_allowed'], ['school_grades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workshops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workshop', sa.String(length=64), nullable=True),
    sa.Column('grade_allowed', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['grade_allowed'], ['school_grades.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workshop')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('last_name_father', sa.String(length=64), nullable=True),
    sa.Column('last_name_mother', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('school', sa.String(length=64), nullable=True),
    sa.Column('kit', sa.Boolean(), nullable=True),
    sa.Column('grade_id', sa.Integer(), nullable=True),
    sa.Column('beverage_id', sa.Integer(), nullable=True),
    sa.Column('user_type_id', sa.Integer(), nullable=True),
    sa.Column('workshop_id', sa.Integer(), nullable=True),
    sa.Column('round_table_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['beverage_id'], ['beverages.id'], ),
    sa.ForeignKeyConstraint(['grade_id'], ['school_grades.id'], ),
    sa.ForeignKeyConstraint(['round_table_id'], ['round_tables.id'], ),
    sa.ForeignKeyConstraint(['user_type_id'], ['user_types.id'], ),
    sa.ForeignKeyConstraint(['workshop_id'], ['workshops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('workshops')
    op.drop_table('round_tables')
    op.drop_table('user_types')
    op.drop_table('staff')
    op.drop_table('school_grades')
    op.drop_table('beverages')
    # ### end Alembic commands ###
